global:
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['host.docker.internal:3000']  

  - job_name: 'tempo'
    scrape_interval: 5s  
    static_configs:
      - targets: ['tempo:80']  
